version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: script/kill_process.sh
      timeout: 100
      runas: ubuntu
  ApplicationStart:
    - location: script/start_process.sh
      timeout: 300
      runas: ubuntu
