$ANSIBLE_VAULT;1.1;AES256
39383337393362323261653733376461623162636239376637633961346537316432353838643431
3663373239613639366434323562643331636337326339630a393831333765653635646365393231
63646232313664393631333934333131356534393532313235346263313835623431633836346636
6234663762666334390a306462653666316531336664656133373034356437323236313837653439
38313130343764333664326461666137303336376631313566343137366637333130333135383564
6632343063646563666565623261376561333962343531323266
