aws_region: ap-northeast-2

# 기존에 만들어둔 EC2(= ansible-server)를 Jenkins로 재활용할 거라서
# "Name" 태그로 찾을 예정
jenkins_instance_name_tag: "project06-ansible-server"

# SSM-only 운영이면 Jenkins를 127.0.0.1로 묶는 게 안전
jenkins_bind_host: "127.0.0.1"
jenkins_http_port: 8080


# 릴리즈 번들(매니페스트/메타) 전용 버킷
s3_bucket_release: project06-dr-release-491085389788-apne2

# DB 백업 전용 버킷
s3_bucket_db: project06-dr-dbbackup-491085389788-apne2

app_name: petclinic
petclinic_manifest_dir: "{{ playbook_dir }}/../../onprem-automation/k8s/petclinic"
petclinic_namespace: petclinic
petclinic_deploy: petclinic


# 이미 성공한 release 버킷(참고)
s3_bucket_release: project06-dr-release-491085389788-apne2

# DB 백업 전용 버킷(너가 만들 이름 - 전세계 유일해야 함)
s3_bucket_db: project06-dr-db-491085389788-apne2

# DB 백업 키 prefix(폴더처럼 보이는 경로)
s3_db_prefix: db-backups/petclinic

mysql_backup_user: "root"
mysql_backup_password: "Team3!@"

aws_region: "ap-northeast-2"

