k8s_minor: "1.34"
k8s_version: "1.34.2"

# 노드망(192.168.20.0/24)과 겹치지 않게!
pod_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"

calico_version: "3.31.3"
calico_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/calico.yaml"
